services:
  - type: web
    name: scheduling-agent-backend-test
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_API_KEY
        sync: false
      - key: BUBBLE_API_TOKEN
        sync: false
      - key: BUBBLE_API_BASE_URL
        value: https://comforthub.ee/version-test/api/1.1/obj
      - key: GEMINI_MODEL
        value: gemini-3.1-flash-lite
      - key: SUPABASE_API_URL
        value: https://dejtvwewomgitszmvsba.supabase.co
      - key: SUPABASE_API_KEY
        sync: false

  - type: web
    name: metabase-analytics
    env: image
    image:
      url: docker.io/metabase/metabase:latest
    plan: free
    region: frankfurt
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        value: postgres
      - key: MB_DB_PORT
        value: "6543"
      - key: MB_DB_USER
        value: postgres.dejtvwewomgitszmvsba
      - key: MB_DB_PASS
        sync: false
      - key: MB_DB_HOST
        value: aws-1-eu-west-2.pooler.supabase.com
